<?php

/**
 * CustomerServiceMetricsFilterCriteriaTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Feed API
 *
 * <p>The <strong>Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-beta
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */
namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;
/**
 * CustomerServiceMetricsFilterCriteriaTest Class Doc Comment
 *
 * @category    Class
 * @description A complex data type that filters data for report creation. See &lt;strong&gt;CustomerServiceMetricsFilterCriteria&lt;/strong&gt; for fields and descriptions.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CustomerServiceMetricsFilterCriteriaTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }
    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }
    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }
    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }
    /**
     * Test "CustomerServiceMetricsFilterCriteria"
     */
    public function testCustomerServiceMetricsFilterCriteria()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test attribute "customer_service_metric_type"
     */
    public function testPropertyCustomerServiceMetricType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test attribute "evaluation_marketplace_id"
     */
    public function testPropertyEvaluationMarketplaceId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test attribute "listing_categories"
     */
    public function testPropertyListingCategories()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test attribute "shipping_regions"
     */
    public function testPropertyShippingRegions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}