<?php

/**
 * SupportedConfigurationTest
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Feed API
 *
 * <p>The <strong>Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-beta
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */
namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;
/**
 * SupportedConfigurationTest Class Doc Comment
 *
 * @category    Class
 * @description An array that defines the configuration supported by this template. This includes specified properties and usage (whether the property is REQUIRED or OPTIONAL), and an optional default value.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SupportedConfigurationTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }
    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }
    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }
    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }
    /**
     * Test "SupportedConfiguration"
     */
    public function testSupportedConfiguration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test attribute "default_value"
     */
    public function testPropertyDefaultValue()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test attribute "property"
     */
    public function testPropertyProperty()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test attribute "usage"
     */
    public function testPropertyUsage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}