<?php

/**
 * ScheduleApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Feed API
 *
 * <p>The <strong>Feed API</strong> lets sellers upload input files, download reports and files including their status, filter reports using URI parameters, and retrieve customer service metrics task details.</p>
 *
 * The version of the OpenAPI document: v1.3.1
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-beta
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPI\Client\Test\Api;

use OpenAPI\Client\Configuration;
use OpenAPI\Client\ApiException;
use OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;
/**
 * ScheduleApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ScheduleApiTest extends TestCase
{
    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }
    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }
    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }
    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }
    /**
     * Test case for createSchedule
     *
     * .
     *
     */
    public function testCreateSchedule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test case for deleteSchedule
     *
     * .
     *
     */
    public function testDeleteSchedule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test case for getLatestResultFile
     *
     * .
     *
     */
    public function testGetLatestResultFile()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test case for getSchedule
     *
     * .
     *
     */
    public function testGetSchedule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test case for getScheduleTemplate
     *
     * .
     *
     */
    public function testGetScheduleTemplate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test case for getScheduleTemplates
     *
     * .
     *
     */
    public function testGetScheduleTemplates()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test case for getSchedules
     *
     * .
     *
     */
    public function testGetSchedules()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
    /**
     * Test case for updateSchedule
     *
     * .
     *
     */
    public function testUpdateSchedule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}